name: Greetings

#on: [pull_request_target, issues]
on: issues
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '# Message with markdown.\nThis is the message that will be displayed on users'
          pr-message: "Message that will be displayed on users"
