name: Greetings

#on: [pull_request_target, issues]
on: issues
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          INPUT_REPO-TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_ISSUE-MESSAGE: "Message that will be displayed on users first issue"
          pr-message: "Message that will be displayed on users first pull request"
